### ISSUE TITLE
Example with subscriptions per user?

### ISSUE THREAD

**Issue by tettoffensive** [MrBoolean/graphql-firestore-subscriptions#16]
Hi, I'm not sure the proper way to do this, but I was looking at your example and wondering how to subscribe users to only new comments that are directed at them.

Do I somehow pass in the `userId` with the options?

```ts
const userHandler: UserHandler = (broadcast, { userId } = { userId: undefined }) => {
  return firebase
    .firestore()
    .collection(`users/${userId}/comments`)
    .onSnapshot((snapshot) => {
      snapshot
        .docChanges()
        .filter((change) => change.type === 'added')
        .map(({ doc }) => broadcast({ id: doc.id, ...doc.data() }));
    });
};
export const pubsub = new PubSub();
pubsub.registerHandler(NEW_COMMENT, (broadcast, options) => userHandler(broadcast, options));
```

I was also looking at using `withFilter`. Not sure if this is the intended usage:

```ts
commentAdded: async (_, { userId }, context) => {
      return withFilter(
        () => pubsub.asyncIterator(NEW_COMMENT),
        (payload, variables) => {
          return payload.comment.commentor === userId;
        },
      );
    },
  },
```

**Comment by inc16sec** [comment]
Thinking about the same thing. @tettoffensive did you manage to know whether this is the right way to implement it. if not, how? Thank you.

**Comment by ethanbonin** [comment]
@inc16sec or @tettoffensive - Did either of you come up with a solution?

**Comment by inc16sec** [comment]
> @inc16sec or @tettoffensive - Did either of you come up with a solution?

I'm using a different database now (Neo4j).

**Comment by tettoffensive** [comment]
No. I haven't been working with firestore lately

**Comment by m19c** [comment]
Yeah, that is the intended usage of withFilter.
