### ISSUE TITLE
[docs] Worthwhile mentioning how to use with subscribeToMore? (+ possible caveats)

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [MrBoolean/graphql-firestore-subscriptions#9]
I was scratching my head for quite a while about the behavior of this (based on the full example) compared to simply publishing directly on mutations with something like graphql-yoga's pubsub.

Seeing how I suppose neither using the `apollo-client`, nor `subscribeToMore` is particularly rare, I wondered whether it would be worth mentioning in the README that if one uses it, one has to skip broadcasting the initial snapshot. (I keep track of it with an `isInitialSnapshot` in the handler.)

This has also made me realize that in a scenario where you have e.g. 1000 documents in that collection and hundreds of people per hour loading up the page, that's a lot of unnecessary load and traffic. Maybe this would also be good to point out?

**Comment by psteinroe** [comment]
I struggled with the same. One key information is that registerHandler gets called every time someone subscribes.

This is how it works for me:

```
ps.registerHandler(events.MESSAGE_ADDED, broadcast => {
  let isInitialSnapshot = true;
  firestore.collectionGroup('Messages').onSnapshot(snapshot => {
    if (isInitialSnapshot) {
      isInitialSnapshot = false;
      return;
    }
    snapshot
      .docChanges()
      .filter(change => change.type === 'added')
      .map(async item => {
        return broadcast({
          chatId: item.doc.ref.parent.parent.id,
          message: item.doc.data(),
        });
      });
  });
});
```
